### ISSUE TITLE
Not an issue per-say

### ISSUE THREAD

**Issue by nameless1** [qwikrazor87/ps1doc#1]
But would it be possible to expand this to also dump psp document.dat manuals? I tried putting one in instead of a psx document.dat but it gave a corrupt manual message when I tried.

**Comment by qwikrazor87** [comment]
I have wrote a PSP version a few years back, but it only dumped the images as they were viewed in the VSH. Give me some time to rewrite the PSP version to have it dump all the PNG images at once like this version.

**Comment by nameless1** [comment]
That would be awesome, npdrm_free and this are great and a psp manual dumper would be icing on the cake!

**Comment by qwikrazor87** [comment]
Here is the PSP game version to dump DOCUMENT.DAT to PNG images.
https://github.com/qwikrazor87/pspdoc/releases
